server:
  port: 8080

spring:
  application:
    name: dataLabel03p5
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

admin:
  username: admin
  password: admin123
